# -*- coding: utf-8 -*-
"""markov-meme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bc_PxixLPiupQfR0JXo-8yWKuFge7EFD
"""

!pip install -q transformers
!pip install -q torch-geometric
!pip install -q pytorch-metric-learning
!pip install -q spacy
!pip install -q scikit-learn

!python -m spacy download en_core_web_sm

from google.colab import drive
drive.mount('/content/drive')

import torch
import spacy
import numpy as np
import pandas as pd
import torch.nn as nn
import torch.nn.functional as F

from PIL import Image
from tqdm import tqdm

from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoProcessor,
    CLIPVisionModel
)

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score
)

from torch.utils.data import (
    Dataset,
    DataLoader
)

from torch_geometric.data import (
    Data,
    Batch
)

from torch_geometric.nn import (
    GATv2Conv,
    global_mean_pool
)

from pytorch_metric_learning.losses import SupConLoss

class CFG:

    TRAIN_CSV="/content/train.csv"

    DEV_CSV="/content/dev.csv"

    DEVICE="cuda" if torch.cuda.is_available() else "cpu"

    TEXT_MODEL="microsoft/deberta-v3-base"

    IMAGE_MODEL="openai/clip-vit-base-patch32"

    MAX_LEN=96

    BATCH_SIZE=8

    EPOCHS=8

    LR=2e-5

    DIM=768

    DROPOUT=0.2

    GRAPH_THRESHOLD=0.65

    ALPHA=0.7

nlp=spacy.load(
    "en_core_web_sm"
)

tokenizer=AutoTokenizer.from_pretrained(
    CFG.TEXT_MODEL
)

text_encoder=AutoModel.from_pretrained(
    CFG.TEXT_MODEL
).to(CFG.DEVICE)

image_processor=AutoProcessor.from_pretrained(
    CFG.IMAGE_MODEL
)

image_encoder=CLIPVisionModel.from_pretrained(
    CFG.IMAGE_MODEL
).to(CFG.DEVICE)

for p in text_encoder.parameters():
    p.requires_grad=False

for p in image_encoder.parameters():
    p.requires_grad=False

@torch.no_grad()
def build_graph(text):

    doc=nlp(text)

    concepts=[]

    dependency_edges=[]

    for token in doc:

        if token.pos_ in [
            "NOUN",
            "PROPN",
            "ADJ"
        ]:

            concepts.append(
                token.text.lower()
            )

        if token.dep_!="ROOT":

            dependency_edges.append([
                token.i,
                token.head.i
            ])

    concepts=list(
        dict.fromkeys(concepts)
    )

    if len(concepts)==0:

        concepts=["empty"]

    encoded=tokenizer(
        concepts,
        padding=True,
        truncation=True,
        max_length=16,
        return_tensors="pt"
    ).to(CFG.DEVICE)

    outputs=text_encoder(
        **encoded
    )

    node_emb=outputs.last_hidden_state[
        :,
        0,
        :
    ].float().cpu()

    sim=F.cosine_similarity(
        node_emb.unsqueeze(1),
        node_emb.unsqueeze(0),
        dim=-1
    )

    edges=[]

    for i in range(len(concepts)):

        for j in range(len(concepts)):

            if i!=j and sim[i][j]>CFG.GRAPH_THRESHOLD:

                edges.append([i,j])

    for u,v in dependency_edges:

        if u<len(concepts) and v<len(concepts):

            edges.append([u,v])

            edges.append([v,u])

    if len(edges)==0:

        edges=[[0,0]]

    edge_index=torch.tensor(
        edges,
        dtype=torch.long
    ).t().contiguous()

    return Data(
        x=node_emb,
        edge_index=edge_index
    )

class MemeDataset(Dataset):

    def __init__(self,csv_path):

        self.df=pd.read_csv(csv_path)

        self.graphs=[]

        for t in tqdm(
            self.df["transcription"]
        ):

            self.graphs.append(
                build_graph(
                    str(t)
                )
            )

    def __len__(self):

        return len(self.df)

    def __getitem__(self,idx):

        row=self.df.iloc[idx]

        image=Image.open(
            row["image_path"]
        ).convert("RGB")

        return {

            "image":image,

            "text":str(
                row["transcription"]
            ),

            "graph":self.graphs[idx],

            "label":torch.tensor(
                row["label"],
                dtype=torch.float32
            )
        }

def collate_fn(batch):

    return {

        "images":[
            x["image"] for x in batch
        ],

        "texts":[
            x["text"] for x in batch
        ],

        "graphs":Batch.from_data_list(
            [x["graph"] for x in batch]
        ),

        "labels":torch.stack([
            x["label"] for x in batch
        ])
    }

class SemanticGraphDiffusion(nn.Module):

    def __init__(self):

        super().__init__()

        self.gat1=GATv2Conv(
            CFG.DIM,
            256,
            heads=4,
            dropout=CFG.DROPOUT
        )

        self.gat2=GATv2Conv(
            1024,
            CFG.DIM,
            heads=1,
            concat=False,
            dropout=CFG.DROPOUT
        )

    def forward(self,graph):

        # x=graph.x.to(CFG.DEVICE)
        x=graph.x.to(CFG.DEVICE).float()

        edge_index=graph.edge_index.to(
            CFG.DEVICE
        )

        batch=graph.batch.to(
            CFG.DEVICE
        )

        h1=self.gat1(
            x,
            edge_index
        )

        h1=F.elu(h1)

        h2=self.gat2(
            h1,
            edge_index
        )

        x=CFG.ALPHA*h2+(1-CFG.ALPHA)*x

        return global_mean_pool(
            x,
            batch
        )

class LatentSemanticTransition(nn.Module):

    def __init__(self):

        super().__init__()

        self.transition=nn.Sequential(

            nn.Linear(
                CFG.DIM*3,
                CFG.DIM
            ),

            nn.LayerNorm(
                CFG.DIM
            ),

            nn.GELU(),

            nn.Dropout(
                CFG.DROPOUT
            )
        )

    def forward(

        self,

        prev_state,

        graph_state,

        image_state
    ):

        state=torch.cat([

            prev_state,
            graph_state,
            image_state

        ],dim=1)

        return self.transition(
            state
        )

# ============================================================
# CROSS MODAL ATTENTION
# ============================================================

class CrossModalAttention(nn.Module):

    def __init__(self):

        super().__init__()

        self.attn=nn.MultiheadAttention(
            CFG.DIM,
            8,
            batch_first=True
        )

    def forward(

        self,

        text_emb,

        image_emb,

        graph_emb
    ):

        q=text_emb.unsqueeze(1)

        kv=torch.stack([

            image_emb,
            graph_emb

        ],dim=1)

        out,_=self.attn(
            q,
            kv,
            kv
        )

        return out.squeeze(1)

class SemanticGraphModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.graph_encoder=SemanticGraphDiffusion()

        self.image_proj=nn.Linear(
            768,
            CFG.DIM
        )

        self.transition=LatentSemanticTransition()

        self.cross_attention=CrossModalAttention()

        self.fusion=nn.Sequential(

            nn.Linear(
                CFG.DIM*4,
                CFG.DIM
            ),

            nn.LayerNorm(
                CFG.DIM
            ),

            nn.GELU(),

            nn.Dropout(
                CFG.DROPOUT
            )
        )

        self.projection=nn.Sequential(

            nn.Linear(
                CFG.DIM,
                256
            ),

            nn.GELU(),

            nn.Linear(
                256,
                128
            )
        )

        self.classifier=nn.Linear(
            CFG.DIM,
            1
        )

    @torch.no_grad()
    def encode_text(self,texts):

        encoded=tokenizer(
            texts,
            padding=True,
            truncation=True,
            max_length=CFG.MAX_LEN,
            return_tensors="pt"
        ).to(CFG.DEVICE)

        outputs=text_encoder(
            **encoded
        )

        return outputs.last_hidden_state[
            :,
            0,
            :
        ].float()

    @torch.no_grad()
    def encode_image(self,images):

        encoded=image_processor(
            images=images,
            return_tensors="pt"
        ).to(CFG.DEVICE)

        outputs=image_encoder(
            **encoded
        )

        return self.image_proj(
            outputs.pooler_output.float()
        )

    def forward(self,batch):

        text_emb=self.encode_text(
            batch["texts"]
        )

        image_emb=self.encode_image(
            batch["images"]
        )

        graph_emb=self.graph_encoder(
            batch["graphs"]
        )

        cross=self.cross_attention(

            text_emb,
            image_emb,
            graph_emb
        )

        latent=self.transition(

            text_emb,
            graph_emb,
            cross
        )

        fusion=torch.cat([

            text_emb,
            image_emb,
            graph_emb,
            latent

        ],dim=1)

        fusion=self.fusion(
            fusion
        )

        logits=self.classifier(
            fusion
        ).squeeze(1)

        proj=F.normalize(

            self.projection(
                fusion
            ),

            dim=1
        )

        return logits,proj

train_dataset=MemeDataset(
    CFG.TRAIN_CSV
)

dev_dataset=MemeDataset(
    CFG.DEV_CSV
)

train_loader=DataLoader(

    train_dataset,

    batch_size=CFG.BATCH_SIZE,

    shuffle=True,

    collate_fn=collate_fn
)

dev_loader=DataLoader(

    dev_dataset,

    batch_size=CFG.BATCH_SIZE,

    shuffle=False,

    collate_fn=collate_fn
)

model=SemanticGraphModel().to(
    CFG.DEVICE
)

criterion=nn.BCEWithLogitsLoss()

supcon=SupConLoss()

optimizer=torch.optim.AdamW(

    model.parameters(),

    lr=CFG.LR
)

@torch.no_grad()
def evaluate(loader):

    model.eval()

    preds=[]

    gold=[]

    for batch in loader:

        labels=batch["labels"].cpu().numpy()

        logits,_=model(batch)

        probs=torch.sigmoid(
            logits
        ).cpu().numpy()

        pred=(probs>0.5).astype(int)

        preds.extend(pred)

        gold.extend(labels)

    acc=accuracy_score(
        gold,
        preds
    )

    f1=f1_score(
        gold,
        preds
    )

    prec=precision_score(
        gold,
        preds
    )

    rec=recall_score(
        gold,
        preds
    )

    return acc,f1,prec,rec

best_f1=0

for epoch in range(CFG.EPOCHS):

    model.train()

    losses=[]

    for batch in tqdm(train_loader):

        labels=batch["labels"].to(
            CFG.DEVICE
        )

        optimizer.zero_grad()

        logits,proj=model(batch)

        cls_loss=criterion(
            logits,
            labels
        )

        cont_loss=supcon(
            proj,
            labels.long()
        )

        loss=cls_loss+0.2*cont_loss

        loss.backward()

        optimizer.step()

        losses.append(
            loss.item()
        )

    acc,f1,prec,rec=evaluate(
        dev_loader
    )

    print(
        f"Epoch {epoch+1}"
    )

    print(
        f"Train Loss: {np.mean(losses):.4f}"
    )

    print(
        f"Accuracy: {acc:.4f}"
    )

    print(
        f"F1: {f1:.4f}"
    )

    print(
        f"Precision: {prec:.4f}"
    )

    print(
        f"Recall: {rec:.4f}"
    )

    if f1>best_f1:

        best_f1=f1

        torch.save(

            model.state_dict(),

            "best_model.pt"
        )

print(
    f"Best F1: {best_f1:.4f}"
)